version: '3.7'
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - /app/node_modules
      - .:/app
    working_dir: /app
    ports:
      - '5000:5000'
    command: yarn turbo run dev --scope=backend
    environment:
      AUTH0_DOMAIN:
      AUTH0_AUDIENCE:
      AUTH0_CLIENT_ID:
      DATABASE_URL: mysql://fga:fga@db:3306/fga
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql:latest
    command: --lower_case_table_names=1
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: fga
      MYSQL_PASSWORD: fga
      MYSQL_DATABASE: fga
