name: CI FE
on: push

jobs:
  test:
    name: Lint, Type check & Test
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Cache node_modules for faster CI runs if the yarn.lock doesn't change change
      - name: Get yarn cache directory path
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Prune
        run: npx turbo prune --scope=frontend

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: out/node_modules/.cache/turbo # workaround see: https://github.com/vercel/turborepo/issues/451
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      # Throw an error if the yarn.lock file doesn't match the installed dependencies (rather than updating it in-place, which it does by default locally)
      - name: Install
        run: |
          cd out
          yarn install --frozen-lockfile --silent

      - name: Lint
        run: |
          cd out
          yarn lint:frontend

      - name: Typecheck
        run: |
          cd out
          yarn typecheck:frontend

      - name: Tests (Jest)
        run: |
          cd out
          yarn test:frontend
